# values.yaml
image:
  repository: metavy/express-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

replicaCount: 1

# Optional: Specify whether to create a service account
serviceAccount:
  create: true
  name: "express-api-service-account"  # Optional: Specify service account name if needed

resources: {}
