apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Disable HTTPS if you're using HTTP
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: api.jipandev.xyz  # Subdomain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-api
                port:
                  number: 80
    - host: jipandev.xyz # Root domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-api
                port:
                  number: 80
