# express-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: express-api
  labels:
    app: express-api
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: {{ .Values.service.type }}
