name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/express-api:${{ github.run_id }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/express-api:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # This ensures the build job runs before this job

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    # Step 2: Update tag in Helm chart
    - name: Update tag in Helm chart
      run: |
        # Update the Helm chart image tag in express-api/values.yaml
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' express-api/values.yaml

    # Step 3: Commit and push changes
    # Step 3: Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.email "${{ secrets.MY_GIT_EMAIL }}"
        git config --global user.name "${{ secrets.MY_GIT_USERNAME }}"
        git add express-api/values.yaml
        git commit -m "Update image tag to ${{ github.run_id }}"
        git push

  install-and-sync-argo-cd:
    runs-on: ubuntu-latest
    needs: update-newtag-in-helm-chart  # Ensure the Helm chart update happens before syncing Argo CD

    steps:
    # Step 1: Install Argo CD CLI
    - name: Install Argo CD CLI
      run: |
        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

    # Step 2: Sync Argo CD
    - name: Sync Argo CD
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }} \
          --insecure
        argocd app sync express-api
