name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/express-api:${{ github.sha }} .
        docker tag your-dockerhub-username/express-api:${{ github.sha }} your-dockerhub-username/express-api:latest
        docker push your-dockerhub-username/express-api:${{ github.sha }}
        docker push your-dockerhub-username/express-api:latest

    # Step 4: Update Helm Chart Values
    - name: Update Helm chart image tag
      run: |
        sed -i "s/tag: .*/tag: ${{ github.sha }}/" helm/express-api/values.yaml
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git commit -am "Update image tag to ${{ github.sha }}"
        git push

    # Step 5: Sync Argo CD
    - name: Sync Argo CD
      run: |
        argocd app sync express-api
