name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/express-api:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/express-api:${{ github.sha }}

    # Step 4: Update Helm Chart Values
    - name: Update Helm chart image tag
      run: |
        sed -i "s/tag: .*/tag: ${{ github.sha }}/" /express-api/values.yaml
        git config --global user.name "${{ secrets.MY_GIT_USERNAME }}"
        git config --global user.email "${{ secrets.MY_GIT_EMAIL }}"
        git add /express-api/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push

    # Step 5: Install Argo CD CLI
    - name: Install Argo CD CLI
      run: |
        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

    # Step 6: Sync Argo CD
    - name: Sync Argo CD
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }} \
          --insecure
        argocd app sync express-api
